baseURL = "https://jianchao-li.github.io/"
title = "Jianchao Li"
languageCode = "en"
defaultContentLanguage = "en"
theme = "blowfish"

enableEmoji = true
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    id = "G-DM5XY5K562"
