[en]
  languageCode = "en"
  languageName = "English"
  weight = 1

  [en.params]
    mainSections = ["posts"]
    description = "Software Engineer with expertise in deep learning and computer vision"

  [en.params.author]
    name = "Jianchao Li"
    image = "img/author.jpg"
    headline = "Software Engineer at Meta"
    bio = "I build with AI."
