[en]
  languageCode = "en"
  languageName = "English"
  weight = 1

  [en.params]
    mainSections = ["post"]
    description = "Software Engineer with expertise in deep learning and computer vision"

  [en.params.author]
    name = "Jianchao Li"
    image = "img/author.jpg"
    headline = "Software Engineer at Meta"
    bio = "I build intelligent systems with deep learning and computer vision."
    links = [
      { github = "https://github.com/jianchao-li" },
      { linkedin = "https://www.linkedin.com/in/jianchao-li/" },
    ]
