[[main]]
  name = "Posts"
  pageRef = "post"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 15

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/jianchao-li"
  weight = 30

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/jianchao-li/"
  weight = 35

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/jianchao2017"
  weight = 36

[[main]]
  identifier = "rss"
  pre = "rss"
  url = "/index.xml"
  weight = 37

[[main]]
  identifier = "appearance"
  weight = 40
  [main.params]
    action = "appearance"
