colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# Blowfish enhancements
showScrollToTop = true

[header]
  layout = "fixed"

[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = true
  sharingLinks = ["linkedin", "twitter", "facebook"]

[list]
  showTableOfContents = false
  showSummary = true
  groupByYear = true
  cardView = true
