colorScheme = "ocean"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# Blowfish enhancements
showScrollToTop = true

[header]
  layout = "fixed"

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  cardView = true
  cardViewScreenWidth = false
  showMoreLink = true
  showMoreLinkDest = "/posts/"

[article]
  showBreadcrumbs = true
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = true
  showRelatedContent = true
  relatedContentLimit = 3
  sharingLinks = ["linkedin", "twitter", "facebook"]

[list]
  showTableOfContents = false
  showSummary = true
  groupByYear = true
  cardView = false
